version: '3'

tasks:

  install:
    - go install github.com/daixiang0/gci@latest
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

  tidy:
    cmds:
      - go mod tidy

  generate:
    cmds:
      - go generate ./...

  lint:
    cmds:
      - go fmt ./...
      - gci write --skip-generated --skip-vendor -s standard -s default -s 'prefix(github.com/panutat-p)' -s localmodule .
      - |
          golangci-lint run \
          --color auto \
          --no-config \
          -E errcheck,gosimple,govet,ineffassign,staticcheck,unused

  dev:
    cmds:
      - go run cmd/main.go
    env:
      APP_NAME: "demo"
      VERSION: "1.0.0"
      PORT: "8080"

  test:
    cmds:
      - go test -v -race -cover -coverprofile=coverage.out ./...

  coverage:
    cmds:
      - go tool cover -html=coverage.out -o coverage.html

  build:
    cmds:
      - go build -o ./bin/app ./cmd/main.go

  build-docker:
    cmds:
      - docker buildx build --platform linux/arm64 -t boilerplate-go:latest .
