version: '3'

tasks:

  tidy:
    cmds:
      - go mod tidy

  lint:
    cmds:
      - go fmt ./...
      - gci write --skip-generated --skip-vendor -s standard -s default -s 'prefix(github.com/panutat-p)' -s localmodule .

  dev:
    cmds:
      - go run cmd/main.go
