version: '3'

tasks:

  tidy:
    cmds:
      - go mod tidy

  generate:
    cmds:
      - go generate ./...

  lint:
    cmds:
      - go fmt ./...
      - gci write --skip-generated --skip-vendor -s standard -s default -s 'prefix(github.com/panutat-p)' -s localmodule .

  dev:
    cmds:
      - go run cmd/main.go
    env:
      APP_NAME: "demo"
      VERSION: "1.0.0"
      PORT: "8201"

  test:
    cmds:
      - go test -v ./...
